### ISSUE TITLE
MM Patching rather than overwriting

### ISSUE THREAD

**Issue by NathanKell** [Pingopete/RVE-KSP-1.0.4#1]
@Pingopete per the forum, I'm happy to fix some of the cfg issues I've seen (as well as converting things to MM patch form, which will make maintenance easier as well as making CKAN possible) but I'd need to do it to your current cfg files--if I do it to these, you'd just commit the new ones and overwrite the changes. :)

**Comment by NathanKell** [comment]
@Pingopete poke :)

**Comment by Pingopete** [comment]
Oh sorry only just understood this ( I'm dumb sometimes ), thanks for the offer but this repo is dead it was just a one-time quick patch and I'll probably end up creating a whole new one for the next upload as it has some serious changes. If you wouldn't mind maybe you could check the configs then but for now please don't worry about RVE :) EDIT: meant this in the nicest way possible, didn't mean to sound blunt or harsh for whatever reason :P Sorry if I've miss understood what you meant, and I'm greatful for your input into RVE :)
